spring.application.name=TenderAPPNew
server.port=8081
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@DESKTOP-DDVO83F:1521:XE
spring.datasource.username=hr
spring.datasource.password=hr

spring.jpa.hibernate.dailect=org.hibernate.dailect.OracleDailect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show.sql=true

# Maximum file size
spring.servlet.multipart.max-file-size=10MB

# Maximum total request size
spring.servlet.multipart.max-request-size=20MB

# Increase file count limit
server.tomcat.max-part-count=20
