spring.application.name=TendorManagementSystem
server.port=8081
spring.datasource.driver-class=oracle.jdbc:driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@LAPTOP-RIIE4K06:1521:XE
spring.datasource.username=system
spring.datasource.password=admin
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql= true
spring.jpa.hibernate.ddl-auto=update
file.upload-dir=C:/Users/PRATIK/uploads/
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB
spring.servlet.multipart.enabled=true





